#!/usr/bin/bash

sudo pacman -Syyu                              # Command to update the repos and to upgrade
yay -Syy                                       # Command to update the repos and to upgrade  (but with Yay)
pacman -Qtdq                                  # Command to list the pacman unused dependencies
if [ $? -eq 0 ];
then sudo pacman -Rns "$(pacman -Qtdq)"        # If the statement is success, then will be deleting the unused dependencies
fi
